(define (my-sort l)
    (if (null? l)
        '()
        (let ((pivot (car l))
              (rest (cdr l)))
          (append (my-sort (filter (lambda (x) (< x pivot))
                                   rest))
                  (list pivot)
                  (my-sort (filter (lambda (x) (>= x pivot))
                                   rest))))))
(display (my-sort '(12 71 2 15 29 82 87 8 18 66 81 25 63 97 40 3 93 58 53 31 47)))
